import {Flags} from '@oclif/core'
import {mkdirSync, writeFileSync} from 'node:fs'
import {dirname, join} from 'node:path'
import {BaseCommand} from '../../lib/base-command.js'

type PipelineTemplate = 'security' | 'full' | 'release' | 'mobile' | 'web3' | 'genai'
type CIPlatform = 'github' | 'gitlab' | 'azure'

// ─── GitHub Actions Templates (v2) ──────────────────────────────────────────

const GITHUB_TEMPLATES: Record<PipelineTemplate, string> = {
  security: `name: OSDO Security Pipeline
# Generated by: osdo pipeline generate --template security --platform github

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  sast:
    name: Static Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SAST Scan
        uses: opensecdevops/osdo-actions/actions/osdo-sast@osdo-sast/v2.0.0
        with:
          path: .
          fail-on-finding: true

  sca:
    name: Dependency Scan (SCA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SCA Scan
        uses: opensecdevops/osdo-actions/actions/osdo-sca@osdo-sca/v2.0.0
        with:
          scanners: osv,grype
          fail-on-critical: true

  secrets:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secrets Scan
        uses: opensecdevops/osdo-actions/actions/osdo-secrets-scan@osdo-secrets-scan/v2.0.0
        with:
          fail-on-finding: true

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: [sast, sca, secrets]
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        uses: opensecdevops/osdo-actions/actions/osdo-sbom@osdo-sbom/v2.0.0
        with:
          format: both
          upload-artifact: true
`,

  full: `name: OSDO Full Pipeline
# Generated by: osdo pipeline generate --template full --platform github

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]

permissions:
  contents: read
  security-events: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: \${{ github.repository }}

jobs:
  sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: opensecdevops/osdo-actions/actions/osdo-sast@osdo-sast/v2.0.0
        with:
          fail-on-finding: true

  sca:
    name: SCA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opensecdevops/osdo-actions/actions/osdo-sca@osdo-sca/v2.0.0
        with:
          fail-on-critical: true

  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: opensecdevops/osdo-actions/actions/osdo-secrets-scan@osdo-secrets-scan/v2.0.0
        with:
          fail-on-finding: true

  build:
    name: Build & Container Scan
    runs-on: ubuntu-latest
    needs: [sast, sca, secrets]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: \${{ env.IMAGE_NAME }}:\${{ github.sha }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Container Scan
        uses: opensecdevops/osdo-actions/actions/osdo-container-scan@osdo-container-scan/v2.0.0
        with:
          image: \${{ env.IMAGE_NAME }}:\${{ github.sha }}
          fail-on: HIGH

  policy:
    name: Policy Gate
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: opensecdevops/osdo-actions/actions/osdo-policy-gate@osdo-policy-gate/v2.0.0
        with:
          builtin-policies: security,compliance
          fail-on-violation: true

  supply-chain:
    name: Supply Chain
    runs-on: ubuntu-latest
    needs: policy
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        uses: opensecdevops/osdo-actions/actions/osdo-sbom@osdo-sbom/v2.0.0
        with:
          format: both
          upload-artifact: true
      - name: Generate Provenance
        if: github.event_name == 'release'
        uses: opensecdevops/osdo-actions/actions/osdo-slsa-provenance@osdo-slsa-provenance/v2.0.0
        with:
          subject-path: dist/*
          slsa-level: "3"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: supply-chain
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Push Container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:latest
            \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:\${{ github.ref_name }}
`,

  release: `name: OSDO Release Pipeline
# Generated by: osdo pipeline generate --template release --platform github

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  security-gate:
    name: Security Gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SAST Scan
        uses: opensecdevops/osdo-actions/actions/osdo-sast@osdo-sast/v2.0.0
        with:
          fail-on-finding: true
      - name: SCA Scan
        uses: opensecdevops/osdo-actions/actions/osdo-sca@osdo-sca/v2.0.0
        with:
          fail-on-critical: true
      - name: Secrets Scan
        uses: opensecdevops/osdo-actions/actions/osdo-secrets-scan@osdo-secrets-scan/v2.0.0
        with:
          fail-on-finding: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: security-gate
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate SBOM
        uses: opensecdevops/osdo-actions/actions/osdo-sbom@osdo-sbom/v2.0.0
        with:
          format: both
          output-prefix: sbom-\${{ github.ref_name }}
          upload-artifact: true
      - name: Sign Artifacts
        uses: opensecdevops/osdo-actions/actions/osdo-signing@osdo-signing/v2.0.0
        with:
          artifacts: dist/*
      - name: Generate Provenance
        uses: opensecdevops/osdo-actions/actions/osdo-slsa-provenance@osdo-slsa-provenance/v2.0.0
        with:
          subject-path: dist/*
          slsa-level: "3"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            .osdo/results/sbom/*
            .osdo/results/slsa/*
`,

  mobile: `name: OSDO Mobile Security Pipeline
# Generated by: osdo pipeline generate --template mobile --platform github
# Standards: OWASP Mobile Top 10 (2024), MASVS

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  security-events: write

jobs:
  mobile-scan:
    name: Mobile Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mobile Security Analysis
        uses: opensecdevops/osdo-actions/actions/osdo-mobile-scan@osdo-mobile-scan/v2.0.0
        with:
          app-path: "."
          platform: "android"
          check-ssl-pinning: true
          check-obfuscation: true
          check-root-detection: true
          check-secrets: true
          fail-on-severity: "HIGH"

  sast:
    name: Static Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: opensecdevops/osdo-actions/actions/osdo-sast@osdo-sast/v2.0.0
        with:
          fail-on-finding: true

  sca:
    name: Dependency Scan (SCA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opensecdevops/osdo-actions/actions/osdo-sca@osdo-sca/v2.0.0
        with:
          fail-on-critical: true

  secrets:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: opensecdevops/osdo-actions/actions/osdo-secrets-scan@osdo-secrets-scan/v2.0.0
        with:
          fail-on-finding: true

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: [mobile-scan, sast, sca, secrets]
    steps:
      - uses: actions/checkout@v4
      - uses: opensecdevops/osdo-actions/actions/osdo-sbom@osdo-sbom/v2.0.0
        with:
          format: both
          upload-artifact: true
`,

  web3: `name: OSDO Web3 Security Pipeline
# Generated by: osdo pipeline generate --template web3 --platform github
# Standards: OWASP Smart Contract Top 10

on:
  push:
    branches: [main, master]
    paths: ['contracts/**', '**/*.sol']
  pull_request:
    paths: ['contracts/**', '**/*.sol']

permissions:
  contents: read
  security-events: write

jobs:
  smart-contract-audit:
    name: Smart Contract Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smart Contract Security Analysis
        uses: opensecdevops/osdo-actions/actions/osdo-smart-contract-audit@osdo-smart-contract-audit/v2.0.0
        with:
          contracts-path: "./contracts"
          scanners: "slither,mythril,solhint"
          solidity-version: "0.8.20"
          check-reentrancy: true
          check-access-control: true
          check-gas-optimization: true
          fail-on-severity: "HIGH"

  sast:
    name: Static Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: opensecdevops/osdo-actions/actions/osdo-sast@osdo-sast/v2.0.0
        with:
          fail-on-finding: true

  sca:
    name: Dependency Scan (SCA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opensecdevops/osdo-actions/actions/osdo-sca@osdo-sca/v2.0.0
        with:
          fail-on-critical: true

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: [smart-contract-audit, sast, sca]
    steps:
      - uses: actions/checkout@v4
      - uses: opensecdevops/osdo-actions/actions/osdo-sbom@osdo-sbom/v2.0.0
        with:
          format: both
          upload-artifact: true
`,

  genai: `name: OSDO GenAI Security Pipeline
# Generated by: osdo pipeline generate --template genai --platform github
# Standards: OWASP GenAI Top 10

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  security-events: write

jobs:
  llm-scan:
    name: LLM/GenAI Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GenAI Security Analysis
        uses: opensecdevops/osdo-actions/actions/osdo-llm-scan@osdo-llm-scan/v2.0.0
        with:
          source-path: "."
          check-prompt-injection: true
          check-pii-exposure: true
          check-model-serialization: true
          check-output-handling: true
          fail-on-severity: "HIGH"

  sast:
    name: Static Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: opensecdevops/osdo-actions/actions/osdo-sast@osdo-sast/v2.0.0
        with:
          fail-on-finding: true

  sca:
    name: Dependency Scan (SCA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opensecdevops/osdo-actions/actions/osdo-sca@osdo-sca/v2.0.0
        with:
          fail-on-critical: true

  secrets:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: opensecdevops/osdo-actions/actions/osdo-secrets-scan@osdo-secrets-scan/v2.0.0
        with:
          fail-on-finding: true

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: [llm-scan, sast, sca, secrets]
    steps:
      - uses: actions/checkout@v4
      - uses: opensecdevops/osdo-actions/actions/osdo-sbom@osdo-sbom/v2.0.0
        with:
          format: both
          upload-artifact: true
`,
}

// ─── GitLab CI Templates ─────────────────────────────────────────────────────

const GITLAB_TEMPLATES: Record<PipelineTemplate, string> = {
  security: `# OSDO Security Pipeline — GitLab CI
# Generated by: osdo pipeline generate --template security --platform gitlab

stages:
  - security
  - sbom

variables:
  OSDO_RESULTS_DIR: ".osdo/results"

sast:
  stage: security
  image: returntocorp/semgrep:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sast
    - semgrep scan --config p/security-audit --config p/owasp-top-ten
        --json --output $OSDO_RESULTS_DIR/sast/semgrep.json .
    - semgrep scan --config p/security-audit . || true
  artifacts:
    reports:
      sast: $OSDO_RESULTS_DIR/sast/semgrep.json
    paths:
      - $OSDO_RESULTS_DIR/sast/
    expire_in: 30 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sca:
  stage: security
  image: anchore/grype:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sca
    - grype dir:. -o json > $OSDO_RESULTS_DIR/sca/grype.json
  artifacts:
    paths:
      - $OSDO_RESULTS_DIR/sca/
    expire_in: 30 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

secrets-scan:
  stage: security
  image: zricethezav/gitleaks:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/secrets
    - gitleaks detect --source=. --report-format=json
        --report-path=$OSDO_RESULTS_DIR/secrets/gitleaks.json
  artifacts:
    paths:
      - $OSDO_RESULTS_DIR/secrets/
    expire_in: 30 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sbom:
  stage: sbom
  image: anchore/syft:latest
  needs: [sast, sca, secrets-scan]
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sbom
    - syft dir:. -o spdx-json=$OSDO_RESULTS_DIR/sbom/sbom.spdx.json
    - syft dir:. -o cyclonedx-json=$OSDO_RESULTS_DIR/sbom/sbom.cdx.json
  artifacts:
    paths:
      - $OSDO_RESULTS_DIR/sbom/
    expire_in: 90 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`,

  full: `# OSDO Full Pipeline — GitLab CI
# Generated by: osdo pipeline generate --template full --platform gitlab

stages:
  - security
  - build
  - policy
  - supply-chain
  - release

variables:
  OSDO_RESULTS_DIR: ".osdo/results"
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

sast:
  stage: security
  image: returntocorp/semgrep:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sast
    - semgrep scan --config p/security-audit --json --output $OSDO_RESULTS_DIR/sast/semgrep.json .
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sast/]
    expire_in: 30 days

sca:
  stage: security
  image: anchore/grype:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sca
    - grype dir:. -o json > $OSDO_RESULTS_DIR/sca/grype.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sca/]
    expire_in: 30 days

secrets-scan:
  stage: security
  image: zricethezav/gitleaks:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/secrets
    - gitleaks detect --source=. --report-format=json --report-path=$OSDO_RESULTS_DIR/secrets/gitleaks.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/secrets/]
    expire_in: 30 days

build:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  needs: [sast, sca, secrets-scan]
  script:
    - docker build -t $IMAGE_TAG .
    - docker save $IMAGE_TAG | gzip > image.tar.gz
    - mkdir -p $OSDO_RESULTS_DIR/container
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock
        aquasec/trivy:latest image --format json --output /dev/stdout $IMAGE_TAG
        > $OSDO_RESULTS_DIR/container/trivy.json || true
  artifacts:
    paths: [$OSDO_RESULTS_DIR/container/, image.tar.gz]
    expire_in: 1 day

sbom:
  stage: supply-chain
  image: anchore/syft:latest
  needs: [build]
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sbom
    - syft dir:. -o spdx-json=$OSDO_RESULTS_DIR/sbom/sbom.spdx.json
    - syft dir:. -o cyclonedx-json=$OSDO_RESULTS_DIR/sbom/sbom.cdx.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sbom/]
    expire_in: 90 days

publish:
  stage: release
  image: docker:24.0
  services:
    - docker:24.0-dind
  needs: [sbom]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
`,

  release: `# OSDO Release Pipeline — GitLab CI
# Generated by: osdo pipeline generate --template release --platform gitlab

stages:
  - security
  - build
  - sign
  - release

variables:
  OSDO_RESULTS_DIR: ".osdo/results"

sast:
  stage: security
  image: returntocorp/semgrep:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sast
    - semgrep scan --config p/security-audit --json --output $OSDO_RESULTS_DIR/sast/semgrep.json .
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sast/]
    expire_in: 30 days
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/

sbom:
  stage: build
  image: anchore/syft:latest
  needs: [sast]
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sbom
    - syft dir:. -o spdx-json=$OSDO_RESULTS_DIR/sbom/sbom-$CI_COMMIT_TAG.spdx.json
    - syft dir:. -o cyclonedx-json=$OSDO_RESULTS_DIR/sbom/sbom-$CI_COMMIT_TAG.cdx.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sbom/]
    expire_in: 365 days
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/

sign-artifacts:
  stage: sign
  image: gcr.io/projectsigstore/cosign:latest
  needs: [sbom]
  script:
    - cosign sign-blob --yes $OSDO_RESULTS_DIR/sbom/sbom-$CI_COMMIT_TAG.spdx.json
        --output-signature $OSDO_RESULTS_DIR/sbom/sbom-$CI_COMMIT_TAG.spdx.json.sig
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: [sign-artifacts]
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG"
    assets:
      links:
        - name: SBOM (SPDX)
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/$OSDO_RESULTS_DIR/sbom/sbom-$CI_COMMIT_TAG.spdx.json"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/
`,

  mobile: `# OSDO Mobile Security Pipeline — GitLab CI
# Generated by: osdo pipeline generate --template mobile --platform gitlab

stages:
  - security
  - sbom

variables:
  OSDO_RESULTS_DIR: ".osdo/results"

mobile-scan:
  stage: security
  image: python:3.11-slim
  script:
    - pip install mobsf-client semgrep
    - mkdir -p $OSDO_RESULTS_DIR/mobile
    - semgrep scan --config p/android --config p/secrets
        --json --output $OSDO_RESULTS_DIR/mobile/semgrep.json . || true
  artifacts:
    paths: [$OSDO_RESULTS_DIR/mobile/]
    expire_in: 30 days

sast:
  stage: security
  image: returntocorp/semgrep:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sast
    - semgrep scan --config p/security-audit --json --output $OSDO_RESULTS_DIR/sast/semgrep.json .
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sast/]
    expire_in: 30 days

sca:
  stage: security
  image: anchore/grype:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sca
    - grype dir:. -o json > $OSDO_RESULTS_DIR/sca/grype.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sca/]
    expire_in: 30 days

secrets-scan:
  stage: security
  image: zricethezav/gitleaks:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/secrets
    - gitleaks detect --source=. --report-format=json --report-path=$OSDO_RESULTS_DIR/secrets/gitleaks.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/secrets/]
    expire_in: 30 days
`,

  web3: `# OSDO Web3 Security Pipeline — GitLab CI
# Generated by: osdo pipeline generate --template web3 --platform gitlab

stages:
  - security
  - sbom

variables:
  OSDO_RESULTS_DIR: ".osdo/results"
  CONTRACTS_DIR: "./contracts"

smart-contract-audit:
  stage: security
  image: trailofbits/eth-security-toolbox:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/smart-contract
    - slither $CONTRACTS_DIR --json $OSDO_RESULTS_DIR/smart-contract/slither.json || true
    - solhint '$CONTRACTS_DIR/**/*.sol' --reporter json
        > $OSDO_RESULTS_DIR/smart-contract/solhint.json || true
  artifacts:
    paths: [$OSDO_RESULTS_DIR/smart-contract/]
    expire_in: 30 days
  rules:
    - changes: [contracts/**/*.sol]

sca:
  stage: security
  image: anchore/grype:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sca
    - grype dir:. -o json > $OSDO_RESULTS_DIR/sca/grype.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sca/]
    expire_in: 30 days

secrets-scan:
  stage: security
  image: zricethezav/gitleaks:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/secrets
    - gitleaks detect --source=. --report-format=json --report-path=$OSDO_RESULTS_DIR/secrets/gitleaks.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/secrets/]
    expire_in: 30 days

sbom:
  stage: sbom
  image: anchore/syft:latest
  needs: [smart-contract-audit, sca, secrets-scan]
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sbom
    - syft dir:. -o cyclonedx-json=$OSDO_RESULTS_DIR/sbom/sbom.cdx.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sbom/]
    expire_in: 90 days
`,

  genai: `# OSDO GenAI Security Pipeline — GitLab CI
# Generated by: osdo pipeline generate --template genai --platform gitlab

stages:
  - security
  - sbom

variables:
  OSDO_RESULTS_DIR: ".osdo/results"

llm-scan:
  stage: security
  image: python:3.11-slim
  script:
    - pip install bandit semgrep detect-secrets
    - mkdir -p $OSDO_RESULTS_DIR/genai
    - semgrep scan --config p/python --config p/secrets
        --json --output $OSDO_RESULTS_DIR/genai/semgrep.json . || true
    - detect-secrets scan . > $OSDO_RESULTS_DIR/genai/detect-secrets.json || true
  artifacts:
    paths: [$OSDO_RESULTS_DIR/genai/]
    expire_in: 30 days

sast:
  stage: security
  image: returntocorp/semgrep:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sast
    - semgrep scan --config p/security-audit --json --output $OSDO_RESULTS_DIR/sast/semgrep.json .
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sast/]
    expire_in: 30 days

sca:
  stage: security
  image: anchore/grype:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/sca
    - grype dir:. -o json > $OSDO_RESULTS_DIR/sca/grype.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/sca/]
    expire_in: 30 days

secrets-scan:
  stage: security
  image: zricethezav/gitleaks:latest
  script:
    - mkdir -p $OSDO_RESULTS_DIR/secrets
    - gitleaks detect --source=. --report-format=json --report-path=$OSDO_RESULTS_DIR/secrets/gitleaks.json
  artifacts:
    paths: [$OSDO_RESULTS_DIR/secrets/]
    expire_in: 30 days
`,
}

// ─── Azure DevOps Templates ──────────────────────────────────────────────────

const AZURE_TEMPLATES: Record<PipelineTemplate, string> = {
  security: `# OSDO Security Pipeline — Azure DevOps
# Generated by: osdo pipeline generate --template security --platform azure

trigger:
  branches:
    include:
      - main
      - master
pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  OSDO_RESULTS_DIR: '.osdo/results'

stages:
  - stage: Security
    displayName: Security Scanning
    jobs:
      - job: SAST
        displayName: Static Analysis (SAST)
        steps:
          - checkout: self
            fetchDepth: 0
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
            displayName: Setup Python
          - script: |
              pip install semgrep
              mkdir -p $(OSDO_RESULTS_DIR)/sast
              semgrep scan --config p/security-audit --config p/owasp-top-ten \\
                --json --output $(OSDO_RESULTS_DIR)/sast/semgrep.json . || true
            displayName: SAST Scan (Semgrep)
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(OSDO_RESULTS_DIR)/sast'
              artifactName: 'sast-results'

      - job: SCA
        displayName: Dependency Scan (SCA)
        steps:
          - checkout: self
          - script: |
              curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
              mkdir -p $(OSDO_RESULTS_DIR)/sca
              grype dir:. -o json > $(OSDO_RESULTS_DIR)/sca/grype.json || true
            displayName: SCA Scan (Grype)
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(OSDO_RESULTS_DIR)/sca'
              artifactName: 'sca-results'

      - job: Secrets
        displayName: Secrets Detection
        steps:
          - checkout: self
            fetchDepth: 0
          - script: |
              brew install gitleaks 2>/dev/null || apt-get install -y gitleaks 2>/dev/null || true
              GITLEAKS_VER=8.18.4
              curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v\${GITLEAKS_VER}/gitleaks_\${GITLEAKS_VER}_linux_x64.tar.gz" | tar -xz -C /tmp
              sudo mv /tmp/gitleaks /usr/local/bin/
              mkdir -p $(OSDO_RESULTS_DIR)/secrets
              gitleaks detect --source=. --report-format=json \\
                --report-path=$(OSDO_RESULTS_DIR)/secrets/gitleaks.json || true
            displayName: Secrets Scan (Gitleaks)
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(OSDO_RESULTS_DIR)/secrets'
              artifactName: 'secrets-results'

  - stage: SBOM
    displayName: Software Bill of Materials
    dependsOn: Security
    condition: succeeded()
    jobs:
      - job: GenerateSBOM
        displayName: Generate SBOM
        steps:
          - checkout: self
          - script: |
              curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
              mkdir -p $(OSDO_RESULTS_DIR)/sbom
              syft dir:. -o spdx-json=$(OSDO_RESULTS_DIR)/sbom/sbom.spdx.json
              syft dir:. -o cyclonedx-json=$(OSDO_RESULTS_DIR)/sbom/sbom.cdx.json
            displayName: Generate SBOM (Syft)
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(OSDO_RESULTS_DIR)/sbom'
              artifactName: 'sbom'
`,

  full: `# OSDO Full Pipeline — Azure DevOps
# Generated by: osdo pipeline generate --template full --platform azure

trigger:
  branches:
    include: [main, master]

pool:
  vmImage: 'ubuntu-latest'

variables:
  OSDO_RESULTS_DIR: '.osdo/results'
  containerRegistry: 'myregistry.azurecr.io'
  imageRepository: 'myapp'
  imageTag: '$(Build.BuildId)'

stages:
  - stage: Security
    displayName: Security Scanning
    jobs:
      - job: SAST
        displayName: SAST
        steps:
          - checkout: self
            fetchDepth: 0
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
          - script: |
              pip install semgrep
              mkdir -p $(OSDO_RESULTS_DIR)/sast
              semgrep scan --config p/security-audit --json --output $(OSDO_RESULTS_DIR)/sast/semgrep.json .
            displayName: SAST Scan

      - job: SCA
        displayName: SCA
        steps:
          - checkout: self
          - script: |
              curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
              mkdir -p $(OSDO_RESULTS_DIR)/sca
              grype dir:. -o json > $(OSDO_RESULTS_DIR)/sca/grype.json
            displayName: SCA Scan

  - stage: Build
    displayName: Build
    dependsOn: Security
    jobs:
      - job: BuildContainer
        displayName: Build & Scan Container
        steps:
          - checkout: self
          - task: Docker@2
            displayName: Build Image
            inputs:
              command: build
              repository: $(imageRepository)
              tags: $(imageTag)
          - script: |
              curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
              mkdir -p $(OSDO_RESULTS_DIR)/container
              trivy image --format json --output $(OSDO_RESULTS_DIR)/container/trivy.json $(imageRepository):$(imageTag)
            displayName: Container Scan (Trivy)

  - stage: SupplyChain
    displayName: Supply Chain
    dependsOn: Build
    jobs:
      - job: SBOM
        displayName: Generate SBOM
        steps:
          - checkout: self
          - script: |
              curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
              mkdir -p $(OSDO_RESULTS_DIR)/sbom
              syft dir:. -o spdx-json=$(OSDO_RESULTS_DIR)/sbom/sbom.spdx.json
              syft dir:. -o cyclonedx-json=$(OSDO_RESULTS_DIR)/sbom/sbom.cdx.json
            displayName: Generate SBOM
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(OSDO_RESULTS_DIR)/sbom'
              artifactName: 'sbom'
`,

  release: `# OSDO Release Pipeline — Azure DevOps
# Generated by: osdo pipeline generate --template release --platform azure

trigger:
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  OSDO_RESULTS_DIR: '.osdo/results'

stages:
  - stage: SecurityGate
    displayName: Security Gate
    jobs:
      - job: SecurityScans
        displayName: Security Scans
        steps:
          - checkout: self
            fetchDepth: 0
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
          - script: |
              pip install semgrep
              semgrep scan --config p/security-audit . --error
            displayName: SAST Gate

  - stage: Release
    displayName: Release
    dependsOn: SecurityGate
    jobs:
      - job: ReleaseArtifacts
        displayName: Release Artifacts
        steps:
          - checkout: self
          - script: |
              curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
              mkdir -p $(OSDO_RESULTS_DIR)/sbom
              syft dir:. -o spdx-json=$(OSDO_RESULTS_DIR)/sbom/sbom-$(Build.BuildNumber).spdx.json
            displayName: Generate SBOM
          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'github'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              tag: '$(Build.SourceBranchName)'
              releaseNotesSource: 'inline'
              assets: '$(OSDO_RESULTS_DIR)/sbom/*'
`,

  mobile: `# OSDO Mobile Security Pipeline — Azure DevOps
# Generated by: osdo pipeline generate --template mobile --platform azure

trigger:
  branches:
    include: [main, master]

pool:
  vmImage: 'ubuntu-latest'

variables:
  OSDO_RESULTS_DIR: '.osdo/results'

stages:
  - stage: MobileSecurity
    displayName: Mobile Security
    jobs:
      - job: MobileScan
        displayName: Mobile Security Scan
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
          - script: |
              pip install semgrep
              mkdir -p $(OSDO_RESULTS_DIR)/sast
              semgrep scan --config p/android --config p/secrets
                --json --output $(OSDO_RESULTS_DIR)/sast/semgrep.json .
            displayName: Mobile SAST Scan
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(OSDO_RESULTS_DIR)/sast'
              artifactName: 'mobile-scan-results'
`,

  web3: `# OSDO Web3 Security Pipeline — Azure DevOps
# Generated by: osdo pipeline generate --template web3 --platform azure

trigger:
  paths:
    include:
      - contracts/**
      - '**/*.sol'

pool:
  vmImage: 'ubuntu-latest'

variables:
  OSDO_RESULTS_DIR: '.osdo/results'
  CONTRACTS_DIR: './contracts'

stages:
  - stage: SmartContractAudit
    displayName: Smart Contract Audit
    jobs:
      - job: AuditContracts
        displayName: Audit Smart Contracts
        container: trailofbits/eth-security-toolbox:latest
        steps:
          - checkout: self
          - script: |
              mkdir -p $(OSDO_RESULTS_DIR)/smart-contract
              slither $(CONTRACTS_DIR) --json $(OSDO_RESULTS_DIR)/smart-contract/slither.json || true
              solhint '$(CONTRACTS_DIR)/**/*.sol' --reporter json
                > $(OSDO_RESULTS_DIR)/smart-contract/solhint.json || true
            displayName: Smart Contract Security Analysis
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(OSDO_RESULTS_DIR)/smart-contract'
              artifactName: 'smart-contract-audit'
`,

  genai: `# OSDO GenAI Security Pipeline — Azure DevOps
# Generated by: osdo pipeline generate --template genai --platform azure

trigger:
  branches:
    include: [main, master]

pool:
  vmImage: 'ubuntu-latest'

variables:
  OSDO_RESULTS_DIR: '.osdo/results'

stages:
  - stage: GenAISecurity
    displayName: GenAI Security Scanning
    jobs:
      - job: LLMScan
        displayName: LLM Security Scan
        steps:
          - checkout: self
            fetchDepth: 0
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
          - script: |
              pip install semgrep bandit detect-secrets
              mkdir -p $(OSDO_RESULTS_DIR)/genai
              semgrep scan --config p/python --config p/secrets
                --json --output $(OSDO_RESULTS_DIR)/genai/semgrep.json .
              detect-secrets scan . > $(OSDO_RESULTS_DIR)/genai/detect-secrets.json || true
            displayName: GenAI Security Analysis
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(OSDO_RESULTS_DIR)/genai'
              artifactName: 'genai-scan-results'
`,
}

function getDefaultOutputPath(platform: CIPlatform, template: PipelineTemplate): string {
  switch (platform) {
    case 'github': return join('.github', 'workflows', `osdo-${template}.yml`)
    case 'gitlab': return '.gitlab-ci.yml'
    case 'azure': return 'azure-pipelines.yml'
  }
}

function getContent(platform: CIPlatform, template: PipelineTemplate): string {
  switch (platform) {
    case 'github': return GITHUB_TEMPLATES[template]
    case 'gitlab': return GITLAB_TEMPLATES[template]
    case 'azure': return AZURE_TEMPLATES[template]
  }
}

export default class PipelineGenerate extends BaseCommand {
  static description = 'Generar archivos de workflow CI/CD con templates OSDO'

  static examples = [
    '<%= config.bin %> pipeline generate --template security',
    '<%= config.bin %> pipeline generate --template full --platform github',
    '<%= config.bin %> pipeline generate --template mobile --platform gitlab',
    '<%= config.bin %> pipeline generate --template web3 --platform azure',
  ]

  static flags = {
    ...BaseCommand.globalFlags,
    template: Flags.string({
      char: 't',
      description: 'Template de pipeline',
      options: ['security', 'full', 'release', 'mobile', 'web3', 'genai'],
      default: 'security',
    }),
    platform: Flags.string({
      char: 'p',
      description: 'Plataforma CI/CD',
      options: ['github', 'gitlab', 'azure'],
      default: 'github',
    }),
    'out-file': Flags.string({
      description: 'Archivo de salida (por defecto según plataforma)',
    }),
  }

  async run(): Promise<void> {
    const {flags} = await this.parse(PipelineGenerate)

    const template = flags.template as PipelineTemplate
    const platform = flags.platform as CIPlatform
    const outputPath = flags['out-file'] ?? getDefaultOutputPath(platform, template)

    this.log('\nOSDO Pipeline Generator')
    this.log('═══════════════════════════════════════')
    this.log(`Plataforma: ${platform}`)
    this.log(`Template:   ${template}`)
    this.log(`Salida:     ${outputPath}\n`)

    if (this.configManager.isDryRun()) {
      this.log(`[dry-run] Generaría pipeline en: ${outputPath}`)
      return
    }

    mkdirSync(dirname(outputPath), {recursive: true})

    const content = getContent(platform, template)
    writeFileSync(outputPath, content, 'utf8')

    this.log(`Pipeline generado: ${outputPath}\n`)
    this.log('Próximos pasos:')
    this.log('  1. Revisa y personaliza el pipeline')
    this.log('  2. Haz commit y push para activar el pipeline')
    this.log('  3. Monitoriza los resultados en tu dashboard CI/CD')
    this.log('  4. Valida el pipeline: osdo pipeline validate')
  }
}
